#!/bin/bash

# Ugly script to package the libqt5pas library for debian.
# Note : 
#	* Based on Lazarus trunk version, its 1.2.8 for now. When Lazarus 3 is
# 	  released it will become 3.0 and then track the Lazarus release number. We don't
#	  want the package name changing with Lazarus releases !
#       * The changelog is tagged by lintian latest-debian-changelog-entry-changed-to-native,
#	  apparently thats a withdrawn error, reflects my use of U18.04, test on recent system !
#	* At run time, Lazarus QT apps appear to try and open libQt5Pas.so.1

#	David Bannon, LGPL with exception, see associated COPYING.TXT 
#	package names look like this -

# intel	libqt5pas1_2.10-0_amd64.deb  		dest = /usr/lib/x86_64-linux-gnu
#	libqt5pas-dev_2.10-0_arm64.deb 

# arm64	libqt5pas-dev_2.10-0_amd64.deb 		dest = 
# 	libqt5pas1_2.10-0_arm64.deb 

# arm32	libqt5pas1_2.10-0_armhf.deb 		dest = /usr/lib/arm-linux-gnueabihf
#	libqt5pas-dev_2.10-0_armhf.deb    

VERSION=`cat ../version`
MAJORVER=`echo $VERSION | awk -F"." '{ printf $1 }'`		# for 1.2.8,  MAJORVER=1
MINORVER=`echo $VERSION | awk -F"." '{ printf $2"."$3 }'`	# for 1.2.8,  MINORVER=2.8
PRODUCT="libqt5pas"	# note lib has upper case letters

ARCH=unknown		# we will set further down. amd64  arm64 and armhf, note: arm64 aka aarch64 ? 
DIR_ARCH=`uname -m`	# Might return, eg aarch64, x86_64. Raspi running 32bit returns armv7l - possibly RasPi version specific ?

VER1=`echo $VERSION | awk -F"." '{ printf $1 }'`		# ie "2"
VER2=`echo $VERSION | awk -F"." '{ printf $1"."$2 }'`		# ie "2.8"
#VER3=`echo $VERSION | awk -F"." '{ printf $2"."$3 }'`

WHOAMI="David Bannon <tomboy-ng@bannons.id.au>"
BUILDDATE=`date -R`

function WriteControl () {
	if [ "$1" = "DEV" ]; then
		echo "Package: $PRODUCT-dev" >> BUILD/DEBIAN/control			
	else
		echo "Package: $PRODUCT$MAJORVER" >> BUILD/DEBIAN/control
		# Next line should mention the source package name we don't have one yet.
		# https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
		# echo "Source: CHANGE-ME" >> BUILD/DEBIAN/control
	fi
	echo "Version: $MINORVER" >> BUILD/DEBIAN/control
	echo "Architecture: ""$ARCH" >> BUILD/DEBIAN/control
	echo "Maintainer: $WHOAMI" >> BUILD/DEBIAN/control
	echo "Priority: optional" >> BUILD/DEBIAN/control
	echo "Multi-Arch: same" >> BUILD/DEBIAN/control
	echo "Homepage: https://wiki.freepascal.org/Qt5_Interface" >> BUILD/DEBIAN/control
	if [ "$1" = "DEV" ]; then
		echo "Installed-Size: 1445" >> BUILD/DEBIAN/control
		echo "Depends: $PRODUCT$MAJORVER (>= $MINORVER), libqt5opengl5-dev, libqt5x11extras5-dev" >> BUILD/DEBIAN/control
		echo "Section: libdevel" >> BUILD/DEBIAN/control
		echo "Description: Development files for Qt5Pas" >> BUILD/DEBIAN/control
	else
		echo "Installed-Size: 3314" >> BUILD/DEBIAN/control
		echo "Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.7.0), libqt5gui5 (>= 5.6.0~beta) | libqt5gui5-gles (>= 5.6.0~beta), libqt5network5 (>= 5.6.0~beta), libqt5printsupport5 (>= 5.2.0), libqt5widgets5 (>= 5.6.0~beta), libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 5)" >> BUILD/DEBIAN/control
		echo "Section: libs" >> BUILD/DEBIAN/control
		echo "Description: Qt5 interface bindings for Pascal" >> BUILD/DEBIAN/control
	fi
	echo " Provides interface for Pascal applications, is only" >> BUILD/DEBIAN/control
	echo " a temp hack until distro versions catch up. It is" >> BUILD/DEBIAN/control
	echo " only really useful, at present, to people using"   >> BUILD/DEBIAN/control
	echo " Lazarus main, current release versions do not need it." >> BUILD/DEBIAN/control
}


function DebianPackage () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/doc/"$PRODUCT$MAJORVER"
	WriteControl
	cp ../libQt5Pas.so."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so."$VERSION"
	strip --remove-section=.comment BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so."$VERSION"
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so."$MAJORVER"
	#ln -s -r BUILD/usr/lib/x86_64-linux-gnu/libQt5Pas.so."$VERSION" BUILD/usr/lib/x86_64-linux-gnu/libQt5Pas.so."$MINORVER"
	#ln -s -r BUILD/usr/lib/x86_64-linux-gnu/libQt5Pas.so."$MAJORVER"."$VERSION" BUILD/usr/lib/x86_64-linux-gnu/libQt5Pas.so."$VER2"
	chmod 0644 BUILD/usr/lib/"$DIR_ARCH"/*
	
    	cp copyright "BUILD/usr/share/doc/$PRODUCT$MAJORVER/copyright"
	
	echo "activate-noawait ldconfig" > BUILD/DEBIAN/triggers
	echo "libQt5Pas $MAJORVER libqt5pas$MAJORVER" > BUILD/DEBIAN/shlibs
	gzip -knc --best changelog.libqt5pas >> BUILD/usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  usr/lib/"$DIR_ARCH"/libQt5Pas.so."$VERSION" > DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT$MAJORVER"_"$MINORVER"-0_"$ARCH".deb
}

function DebianPackageDev () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/pascal/qt5
	mkdir -p BUILD/usr/share/doc/"$PRODUCT"-dev
	WriteControl DEV
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/libQt5Pas.so
	cp ../qt5.pas BUILD/usr/share/pascal/qt5/.
	chmod 0644 BUILD/usr/share/pascal/qt5/*
    	cp copyright BUILD/usr/share/doc/"$PRODUCT-dev"/copyright
	gzip -knc --best changelog.libqt5pas >> BUILD/usr/share/doc/"$PRODUCT-dev"/changelog.gz
 
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  "usr/share/pascal/qt5/qt5.pas" > DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"-dev_"$MINORVER"-0_"$ARCH".deb
}

if [ "$DIR_ARCH" == "aarch64" ]; then
	ARCH="arm64"			# Name used in deb file name
	DIR_ARCH="aarch64-linux-gnu"	# Dir where the libraries end up
fi
if [ "$DIR_ARCH" == "armv7l" ]; then
	ARCH="armhf"
	DIR_ARCH="arm-linux-gnueabihf"
fi
if [ "$DIR_ARCH" == "x86_64" ]; then
	ARCH="amd64"
	DIR_ARCH="x86_64-linux-gnu"
fi
if [ "$ARCH" == "unknown" ]; then
	echo "ERROR cannot id your arch $DIR_ARCH, exiting..."
	exit
fi

echo "Building for $ARCH $DIR_ARCH - hope thats OK"

# strip ../libQt5Pas.so."$VERSION"

DebianPackage 
DebianPackageDev

lintian -IiE *.deb

ls -ltr *.deb




