#!/bin/bash
# 
# A script to package the pre-built libqt6pas library into debs, rpms and a tarball
# 	New - rpms and now not build with alien and are also a much higher quality.
#       Tested on, so far, on a amd64 box, there will be issues on arm
#	Resonable lintian and rpmlint result. See end of script !
#
#	    David Bannon 2022-11-25
# NAMING
#	Hard to be sure, no clear definition and varying conventions in use but -
#	ftp.debian.org/debian/pool/main/q/qt6-base - typical...
#	libqt6opengl6-dev_6.4.1-1_armhf.deb
#	libqt6opengl6_6.3.1-1_i386.deb
#	Note that the '6' appears 3 times but in each case refers to the same thing !
#	So, we always have a name including 'qt6' then ending in'6' and then a VerNo starting with '6'
#	And all three '6' are both in main package and -dev package.
#	And the number of the beast shall be 666 .....
#	The actual, binary library file is libQt6OpenGL.so.6.4.1 so the trailing '6' on the name has dissapeared !
# 	So, we will do - 
#		Library, binary libQt6Pas.so.6.2.3
#		Package,        libqt6pas6_6.2.0-1_amd64.deb 
#		Dev Package     libqt6pas6-dev.6.2.0-1_amd64.deb
# 	The '0' in above will be rev'ed by every change Z makes to the interface, the 6.2 is the LTS Qt6 release


PACKVER='2'		# should start at '1', rev if you re-package same binary

LIBNAME=libQt5Pas
PRODUCT="libqt5pas"	# lib has upper case Q - P, this appears in Package name, add '1' to lib, -dev to devlib
CURRENT=`pwd`

	# library will be called something like ./libQt6Pas.so.6.2.3, the package libqt6pas6_6.2.0-1_amd64.deb and libqt6pas6-dev.6.2.0-1_amd64
	cd ..
	LIBFILE=$(find . -maxdepth 1 ! -type l  -name "$LIBNAME""*")
	cd $CURRENT
	MAJORVER=`echo $LIBFILE | awk -F"." '{ printf $4 }'`	# for 6.2.0, = 7
	MINORVER=`echo $LIBFILE | awk -F"." '{ printf $5 }'`	#	     = 2
	EXTRAVER=`echo $LIBFILE | awk -F"." '{ printf $6 }'`	#	     = 0
	# VERSION="$MAJORVER"."$MINORVER"."$EXTRAVER"    no, due to history of these packages, don't use Major
	VERSION="$MINORVER"."$EXTRAVER"
echo "Name=$LIBFILE, Maj=$MAJORVER, Minor=$MINORVER, extra=$EXTRAVER, VERSION=$VERSION" 
# ToDo : really should have some sanity checks here

FULLLIBNAME="$LIBNAME".so."$MAJORVER"."$VERSION"



ARCH=unknown		# we will set further down. amd64  arm64 and armhf, note: arm64 aka aarch64 ? 
DIR_ARCH=unknown
M_ARCH=`uname -m`	# Might return, eg aarch64, x86_64. Raspi running 32bit returns armv7l - possibly RasPi version specific ?

WHOAMI="David Bannon <tomboy-ng@bannons.id.au>"
BUILDDATE=`date -R`

function WriteControl () {
	if [ "$1" = "DEV" ]; then
		echo "Package: $PRODUCT-dev" >> BUILD/DEBIAN/control			
	else
		echo "Package: $PRODUCT" >> BUILD/DEBIAN/control
		# Next line should mention the source package name we don't have one yet.
		# https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
		# echo "Source: CHANGE-ME" >> BUILD/DEBIAN/control
	fi
	echo "Version: ""$MAJORVER"."$MINORVER"."$EXTRAVER" >> BUILD/DEBIAN/control
	echo "Architecture: ""$ARCH" >> BUILD/DEBIAN/control
	echo "Maintainer: $WHOAMI" >> BUILD/DEBIAN/control
	echo "Priority: optional" >> BUILD/DEBIAN/control
	echo "Multi-Arch: same" >> BUILD/DEBIAN/control
	echo "Homepage: https://wiki.freepascal.org/Qt6_Interface" >> BUILD/DEBIAN/control
	# ----- I am not sure if the following is a good idea or not, no, better without, as is replaces old ver, might get new version next
	# echo "Replaces: libqt5pas1" >> BUILD/DEBIAN/control


	SIZE_IN_KB="$(du -s BUILD | awk '{print $1;}')"
	echo "Installed-Size: ${SIZE_IN_KB}" >> BUILD/DEBIAN/control

	if [ "$1" = "DEV" ]; then
		# echo "Installed-Size: 1445" >> BUILD/DEBIAN/control
		echo "Depends: $PRODUCT (>= $MAJORVER.$MINORVER.$EXTRAVER), libqt5opengl5-dev, libqt5x11extras5-dev" >> BUILD/DEBIAN/control
		echo "Section: libdevel" >> BUILD/DEBIAN/control
		echo "Description: Development files for Qt6Pas" >> BUILD/DEBIAN/control
	else
		# echo "Installed-Size: 3314" >> BUILD/DEBIAN/control
		
		echo "Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.7.0), libqt5gui5 (>= 5.6.0~beta) | libqt5gui5-gles (>= 5.6.0~beta), libqt5network5 (>= 5.6.0~beta), libqt5printsupport5 (>= 5.2.0), libqt5widgets5 (>= 5.6.0~beta), libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 5)" >> BUILD/DEBIAN/control

		echo "Section: libs" >> BUILD/DEBIAN/control
		echo "Description: Qt5 interface bindings for Pascal" >> BUILD/DEBIAN/control
	fi
	echo " Provides interface for Pascal applications, is only" >> BUILD/DEBIAN/control
	echo " a temp hack until distributions catch up. It is" >> BUILD/DEBIAN/control
	echo " only really useful, at present, to people using"   >> BUILD/DEBIAN/control
	echo " Lazarus main, current release versions do not need it." >> BUILD/DEBIAN/control
}


function DebianPackage () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/doc/"$PRODUCT"
	WriteControl
	cp ../"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/.
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"
	# Don't link to base name, Lintian objects 'cos thats the -dev package's job
	chmod 0644 BUILD/usr/lib/"$DIR_ARCH"/*
	
    cp copyright "BUILD/usr/share/doc/$PRODUCT/copyright"
	
	echo "activate-noawait ldconfig" > BUILD/DEBIAN/triggers
	echo "libQt5Pas $MAJORVER libqt5pas$MAJORVER" > BUILD/DEBIAN/shlibs
	gzip -knc --best changelog.libqt5pas >> BUILD/usr/share/doc/"$PRODUCT"/changelog.gz
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$VERSION" > DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"1_"$VERSION"-"$PACKVER"_"$ARCH".deb
}

function DebianPackageDev () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/pascal/qt5
	mkdir -p BUILD/usr/share/doc/"$PRODUCT"-dev
	WriteControl DEV
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so
	cp ../qt5.pas BUILD/usr/share/pascal/qt5/.
	#cp ../qt62.pas BUILD/usr/share/pascal/qt6/.
	chmod 0644 BUILD/usr/share/pascal/qt5/*
    cp copyright BUILD/usr/share/doc/"$PRODUCT-dev"/copyright
	gzip -knc --best changelog.libqt5pas >> BUILD/usr/share/doc/"$PRODUCT-dev"/changelog.gz
 
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  "usr/share/pascal/qt5/qt5.pas" > DEBIAN/md5sums
	#md5sum  "usr/share/pascal/qt6/qt62.pas" >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"-dev_"$VERSION"-"$PACKVER"_"$ARCH".deb
}

# A lot more work is required for this to work even on non amd64 hardware.
# Paricularly where the library is supposed to end up !
#

# We want a dir name like this - libqt6pas6-2.2

function MakeRPM () {
	# PARTVER="$MAJORVER"."$MINORVER"."$EXTRAVER"
	# VERSION="$MAJORVER"."$VERSION"
	FULLVER="$MAJORVER"."$VERSION"-"$PACKVER"
    RDIR="$PRODUCT"-"$MAJORVER"."$VERSION"
    echo "=== Making RPM from $PRODUCT"."$FULLVER"_"$ARCH.deb in $RDIR ==="
    rm -Rf "$RDIR"
	mkdir -p "$RDIR"/usr/"$RDIR_ARCH"
	chmod 744 "$RDIR"/usr/"$RDIR_ARCH"
	# mkdir -p "$RDIR"/usr/lib
	if [ "$1" = "devel" ]; then		# DEV Package
		echo "========= RPM Devel Package ========"
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"-devel
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"-devel
    		cp copyright "$RDIR"/usr/share/doc/"$PRODUCT"-devel/copyright
		gzip -knc --best changelog.libqt5pas >> "$RDIR"/usr/share/doc/"$PRODUCT"-devel/changelog.gz
		cd "$RDIR"/usr/"$RDIR_ARCH"
		ln -s "$FULLLIBNAME" "$LIBNAME".so
		cd "$CURRENT"
		# ln -s /usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so
		# ln -s "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so
    	cp ../qt5.pas "$RDIR/usr/share/doc/"$PRODUCT"-devel/."
    	#cp ../qt62.pas "$RDIR/usr/share/doc/"$PRODUCT"-devel/."
		cp libqt5pas-devel.spec "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_DEPEND/${PRODUCT} = ${MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_RDIR/${RDIR}/" "$RDIR"/"$PRODUCT".spec
	else	
		echo "========= RPM Lib Package =========="
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"
    		cp copyright "$RDIR/usr/share/doc/"$PRODUCT"/copyright"
		gzip -knc --best changelog.libqt5pas >> "$RDIR"/usr/share/doc/"$PRODUCT"/changelog.gz
		cp ../"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/.
		chmod 755 "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"
		cp libqt5pas.spec "$RDIR"/"$PRODUCT".spec
	fi
	sed -i "s/^Version:*./Version: ${MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/^Release:*./Release: ${PACKVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_FULL_VER/Version: ${FULLVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_VERSION/${MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
	cp -f "$RDIR"/"$PRODUCT".spec "$PRODUCT""$1".spec-just-used
	cd "$RDIR"
	fakeroot rpmbuild --target "$M_ARCH" --buildroot "$CURRENT"/"$RDIR" -bb "$PRODUCT".spec
	cd .. 
}


if [ "$M_ARCH" == "aarch64" ]; then
	ARCH="arm64"			# Name used in deb file name
	DIR_ARCH="aarch64-linux-gnu"	# Dir where the libraries end up
	RDIR_ARCH="lib64"		# Where RPMs put the library         TODO !!!
fi
if [ "$M_ARCH" == "armv7l" ]; then
	ARCH="armhf"
	DIR_ARCH="arm-linux-gnueabihf"
	RDIR_ARCH="lib"		# Where RPMs put the library         TODO !!!
fi
if [ "$M_ARCH" == "x86_64" ]; then
	ARCH="amd64"
	DIR_ARCH="x86_64-linux-gnu"
	RDIR_ARCH="lib64"		# Where RPMs put the library 
fi
if [ "$ARCH" == "unknown" ]; then
	echo "ERROR cannot id your arch $DIR_ARCH, exiting..."
	exit
fi

echo "Building for $ARCH to go into $DIR_ARCH - Maj=""$MAJORVER"", Min=""$MINORVER"", EXTRA=""$EXTRAVER"

rm -f *.deb *.rpm *.gz

strip --remove-section=.comment ../"$FULLLIBNAME"

DebianPackage 
DebianPackageDev
echo " ====== Finished Building Debs ======="
MakeRPM   
MakeRPM "devel"       

TARNAME=libqt5pas_"$MAJORVER"_"$MINORVER"_"$EXTRAVER"-"$PACKVER"_"$ARCH"
rm -Rf "$TARNAME"
mkdir "$TARNAME"
cp targz.readme "$TARNAME"/.
cp ../"$FULLLIBNAME" "$TARNAME"/.
tar czf "$TARNAME".tar.gz "$TARNAME"
rm -Rf "$TARNAME"
rm -Rf BUILD
ls -ltr

# ------- RESTORE ME --------------- lintian -IiE *.deb

#echo " === OK, now make the rpms with   fakeroot bash ./rpm-package.bash   <enter> ==="


# --------------- RPM LINT Issues ------------------------------

# libqt6pas6.x86_64: E: library-without-ldconfig-postin
# libqt6pas6.x86_64: E: library-without-ldconfig-postun
#    Not required anymore -
#    https://fedoraproject.org/wiki/Changes/Removing_ldconfig_scriptlets

# libqt6pas6.x86_64: W: invalid-license see /usr/share/doc/libqt6pas6/copyright
#    The license is fine, its just that rpmlint cannot parse it.

# libqt6pas6.x86_64: E: no-signature
#    As near as I can tell, only OpenSUSE seems to care about signitures.

# no-binary
#    Rpmlint thinks it should be "noarch" because there is no binary but 
#    it provides a symling, in an appropriate binary dir, to a binary !

# --------------- Lintian Issues ---------------------------------

# No-Symbol-control-file
#    Yeah, no symbol control file.

# No-hardening
#    Personally, I don't thing hardening is needed in the sort of apps
#    likely to be working with this library but I am happy to hear any
#    other opinions on this matter. Its easy to do but a bit slower.
#    And its really a decision for the Lazarus Qt6 developer.


