#!/bin/bash
#
# Usage : eg  DEBEMAIL=tomboy-ng@bannons.id.au DEBFULLNAME="David Bannon" bash ./package-lib <enter>
#
# Remember, rpms may not be signed, on right box, rpm --addsign something.rpm <enter>
#           for i in `ls -b *.rpm`; do rpm --addsign "$i"; echo "Signed $i"; done
#
#           
# A script to package the pre-built libqt5pas library into debs, rpms and a tarball
# 	New - rpms and now not build with alien and are also a much higher quality.
#       Tested on, so far, on a amd64 box, there will be issues on arm cos no rpmlint !
#	Reasonable lintian and rpmlint result. See end of script !
#	must get DEBEMAIL=tomboy-ng@bannons.id.au DEBFULLNAME="David Bannon" in env.
#	Require devscripts, lintian, gcc....
#
#	    David Bannon 2022-11-25

PACKVER='3'		# should start at '1', rev if you re-package same binary

LIBNAME=libQt5Pas
PRODUCT="libqt5pas"	# lib has upper case Q - P, this appears in Package name, add '1' to lib, -dev to devlib
CURRENT=`pwd`

	# library will be called something like -
	# libQt5Pas.so.1.2.14, the package libqt5pas1_2.14-1_amd64.deb and libqt5pas-dev_2.14-1_amd64
	# libqt5pas-1.2.14-1.x86_64.rpm and libqt5pas-devel-1.2.14-1.x86_64.rpm
	cd ..
	LIBFILE=$(find . -maxdepth 1 ! -type l  -name "$LIBNAME""*")
	cd $CURRENT
	MAJORVER=`echo $LIBFILE | awk -F"." '{ printf $4 }'`	# for 6.2.0, = 7
	MINORVER=`echo $LIBFILE | awk -F"." '{ printf $5 }'`	#	     = 2
	EXTRAVER=`echo $LIBFILE | awk -F"." '{ printf $6 }'`	#	     = 0
	# VERSION="$MAJORVER"."$MINORVER"."$EXTRAVER"    no, due to history of these packages, don't use Major
	VERSION="$MINORVER"."$EXTRAVER"
echo "Name=$LIBFILE, Maj=$MAJORVER, Minor=$MINORVER, extra=$EXTRAVER, VERSION=$VERSION" 
# ToDo : really should have some sanity checks here

FULLLIBNAME="$LIBNAME".so."$MAJORVER"."$VERSION"



ARCH=unknown		# we will set further down. amd64  arm64 and armhf, note: arm64 aka aarch64 ? 
DIR_ARCH=unknown
M_ARCH=`uname -m`	# Might return, eg aarch64, x86_64, i686. Raspi running 32bit returns armv7l - possibly RasPi version specific ?

WHOAMI="David Bannon <tomboy-ng@bannons.id.au>"
BUILDDATE=`date -R`



function WriteControl () {
	if [ "$1" = "DEV" ]; then
		echo "Package: $PRODUCT-dev" >> BUILD/DEBIAN/control			
	else
		echo "Package: $PRODUCT"1 >> BUILD/DEBIAN/control
		# Next line should mention the source package name we don't have one yet.
		# https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
		# echo "Source: CHANGE-ME" >> BUILD/DEBIAN/control
	fi
#	echo "Version: ""$MAJORVER"."$MINORVER"."$EXTRAVER" >> BUILD/DEBIAN/control
	echo "Version: ""$MINORVER"."$EXTRAVER" >> BUILD/DEBIAN/control
	echo "Architecture: ""$ARCH" >> BUILD/DEBIAN/control
	echo "Maintainer: $WHOAMI" >> BUILD/DEBIAN/control
	echo "Priority: optional" >> BUILD/DEBIAN/control
	echo "Multi-Arch: same" >> BUILD/DEBIAN/control
	echo "Homepage: https://wiki.freepascal.org/Qt5_Interface" >> BUILD/DEBIAN/control
	# ----- I am not sure if the following is a good idea or not, no, better without, as is replaces old ver, might get new version next
#    echo "Breaks: libqt5pas1 (<= 2.6)" >> BUILD/DEBIAN/control
#	echo "Replaces: libqt5pas1 (<= 2.6)" >> BUILD/DEBIAN/control         # Older distro packages before formalising ver no were called this


	SIZE_IN_KB="$(du -s BUILD | awk '{print $1;}')"
	echo "Installed-Size: ${SIZE_IN_KB}" >> BUILD/DEBIAN/control

	if [ "$1" = "DEV" ]; then
		# echo "Installed-Size: 1445" >> BUILD/DEBIAN/control
		echo "Depends: $PRODUCT""1 (>= $MINORVER.$EXTRAVER), libqt5opengl5-dev, libqt5x11extras5-dev" >> BUILD/DEBIAN/control
		echo "Section: libdevel" >> BUILD/DEBIAN/control
		echo "Description: Development files for Qt5Pas" >> BUILD/DEBIAN/control
	else
		# echo "Installed-Size: 3314" >> BUILD/DEBIAN/control
		
		echo "Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.7.0), libqt5gui5 (>= 5.6.0~beta) | libqt5gui5-gles (>= 5.6.0~beta), libqt5network5 (>= 5.6.0~beta), libqt5printsupport5 (>= 5.2.0), libqt5widgets5 (>= 5.6.0~beta), libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 5)" >> BUILD/DEBIAN/control

		echo "Section: libs" >> BUILD/DEBIAN/control
		echo "Description: Qt5 interface bindings for Pascal" >> BUILD/DEBIAN/control
	fi
	echo " Provides interface for Pascal applications, is only" >> BUILD/DEBIAN/control
	echo " a temp hack until distributions catch up. It is" >> BUILD/DEBIAN/control
	echo " only really useful, at present, to people using"   >> BUILD/DEBIAN/control
	echo " Lazarus main, current release versions do not need it." >> BUILD/DEBIAN/control

cp BUILD/DEBIAN/control control."$1"
}


function DebianPackage () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/doc/"$PRODUCT""$MAJORVER"
	WriteControl
	cp ../"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/.
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"
	# Don't link to base name, Lintian objects 'cos thats the -dev package's job
	chmod 0644 BUILD/usr/lib/"$DIR_ARCH"/*
	
    cp copyright "BUILD/usr/share/doc/$PRODUCT$MAJORVER/copyright"
	
	echo "activate-noawait ldconfig" > BUILD/DEBIAN/triggers
	echo "libQt5Pas $MAJORVER libqt5pas$MAJORVER" > BUILD/DEBIAN/shlibs
	if [ "$M_ARCH" == "x86_64" ]; then					# only write changelog on first run, x86_64 
		dch -cchangelog -v "$MAJORVER"."$MINORVER"."$EXTRAVER" -D"unstable" "Release of new version."   
		if [ -f whatsnew ]; then
	   		echo "---------- Including whatsnew in changelog"
	   		while IFS= read -r Line; do
			dch -cchangelog --append "$Line"
	   		done < whatsnew
		fi
	fi
	dch -cchangelog --append "Please see Lazarus at gitlab for further change details."
	
	gzip -knc --best changelog >> BUILD/usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz
	ls -l BUILD/usr/share/doc/"$PRODUCT$MAJORVER"
	gzip -knc --best changelog >> changelog.gz
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$VERSION" > DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
	du -hs BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"1_"$VERSION"-"$PACKVER"_"$ARCH".deb
}

function DebianPackageDev () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/pascal/qt5
	mkdir -p BUILD/usr/share/doc/"$PRODUCT"-dev
	WriteControl DEV
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so
	cp ../qt5.pas BUILD/usr/share/pascal/qt5/.
	#cp ../qt62.pas BUILD/usr/share/pascal/qt6/.
	chmod 0644 BUILD/usr/share/pascal/qt5/*
    cp copyright BUILD/usr/share/doc/"$PRODUCT-dev"/copyright
	gzip -knc --best changelog >> BUILD/usr/share/doc/"$PRODUCT-dev"/changelog.gz
 
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  "usr/share/pascal/qt5/qt5.pas" > DEBIAN/md5sums
	#md5sum  "usr/share/pascal/qt6/qt62.pas" >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"-dev_"$VERSION"-"$PACKVER"_"$ARCH".deb
}

# A lot more work is required for this to work even on non amd64 hardware.
# Paricularly where the library is supposed to end up !
#

# We want a dir name like this - libqt6pas6-2.2

function MakeRPM () {
	# FULLVER="$MAJORVER"."$VERSION"-"$PACKVER"    # MAJORVER = 1. n.a.
	FULLVER="$VERSION"-"$PACKVER"
    # RDIR="$PRODUCT"-"$MAJORVER"."$VERSION"
    RDIR="$PRODUCT"-"$VERSION"
    echo "=== Making RPM from $PRODUCT"."$FULLVER"_"$ARCH.deb in $RDIR ==="
    rm -Rf "$RDIR"
	mkdir -p "$RDIR"/usr/"$RDIR_ARCH"
	chmod 744 "$RDIR"/usr/"$RDIR_ARCH"
	# mkdir -p "$RDIR"/usr/lib
	if [ "$1" = "devel" ]; then		# DEV Package
		echo "========= RPM Devel Package ========"
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"-devel
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"-devel
    	cp copyright "$RDIR"/usr/share/doc/"$PRODUCT"-devel/copyright
		gzip -knc --best changelog >> "$RDIR"/usr/share/doc/"$PRODUCT"-devel/changelog.gz
		cd "$RDIR"/usr/"$RDIR_ARCH"
		ln -s "$FULLLIBNAME" "$LIBNAME".so
		cd "$CURRENT"
		# ln -s /usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so
		# ln -s "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so
    	cp ../qt5.pas "$RDIR/usr/share/doc/"$PRODUCT"-devel/."
    	#cp ../qt62.pas "$RDIR/usr/share/doc/"$PRODUCT"-devel/."
		cp libqt5pas-devel.spec "$RDIR"/"$PRODUCT".spec
		# sed -i "s/INSERT_DEPEND/${PRODUCT} = {MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_DEPEND/${PRODUCT} = ${VERSION}/" "$RDIR"/"$PRODUCT".spec
		# sed -i "s/INSERT_RDIR/${RDIR}/" "$RDIR"/"$PRODUCT".spec
	else	
		echo "========= RPM Lib Package =========="
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"
    	cp copyright "$RDIR/usr/share/doc/"$PRODUCT"/copyright"
		gzip -knc --best changelog >> "$RDIR"/usr/share/doc/"$PRODUCT"/changelog.gz
		cp ../"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/.
		chmod 755 "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"
		cp libqt5pas.spec "$RDIR"/"$PRODUCT".spec
	fi
	# sed -i "s/^Version:*./Version: ${MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/^Version:*./Version: ${VERSION}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/^Release:*./Release: ${PACKVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_FULL_VER/Version: ${FULLVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_EXTRAVER/${EXTRAVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_RDIR/${RDIR}/" "$RDIR"/"$PRODUCT".spec

	cp -f "$RDIR"/"$PRODUCT".spec "$PRODUCT""$1".spec-just-used
	cd "$RDIR"
	fakeroot rpmbuild --target "$M_ARCH" --buildroot "$CURRENT"/"$RDIR" -bb "$PRODUCT".spec
	cd .. 
}


if [ "$M_ARCH" == "aarch64" ]; then	# OK, arm64 hardware but maybe 32bit OS ?
	OSBITNESS=`getconf LONG_BIT`
	if [ "$OSBITNESS" == "32" ]; then
	    echo "NOTE : 32bit OS running on 64bit arm hardware"
	    ARCH="armv7hl"              # Mageia 9 includes 'h' - hard float ?
	    DIR_ARCH="arm-linux-gnueabihf"
	    RDIR_ARCH="lib"
	    M_ARCH="$ARCH"
	else
	    ARCH="arm64"			# Name used in deb file name
	    DIR_ARCH="aarch64-linux-gnu"	# Dir where the libraries end up
	    RDIR_ARCH="lib64"		# Where RPMs put the library        
	fi
fi
if [ "$M_ARCH" == "armv7l" ]; then		# 32 bit arm, eg raspi
	ARCH="armhf"
	DIR_ARCH="arm-linux-gnueabihf"
	RDIR_ARCH="lib"		# Where RPMs put the library         TODO !!!
fi
if [ "$M_ARCH" == "x86_64" ]; then
	ARCH="amd64"
	DIR_ARCH="x86_64-linux-gnu"
	RDIR_ARCH="lib64"		# Where RPMs put the library 
fi
if [ "$M_ARCH" == "i686" ]; then	# eg, debian 32 bit
	ARCH="i386"
	DIR_ARCH="i386-linux-gnu"
	RDIR_ARCH="lib"			# A guess ? Where RPMs put the library 
fi
if [ "$ARCH" == "unknown" ]; then
	echo "ERROR cannot id your arch $DIR_ARCH, exiting..."
	exit
fi

echo "Building for $ARCH to go into $DIR_ARCH - Maj=""$MAJORVER"", Min=""$MINORVER"", EXTRA=""$EXTRAVER"

rm -f *.deb *.rpm *.gz

strip --remove-section=.comment ../"$FULLLIBNAME"

DebianPackage 				# do before dev package because it updates the changelog
DebianPackageDev
echo " ====== Finished Building Debs ======="
MakeRPM   
MakeRPM "devel"  
# OK, lets sign the RPMs, requires ~/.rpmmacro to tell us which gpg key to use.
echo "Davo - use long pass phrase !"     
for i in `ls -b *.rpm`; do rpm --addsign "$i"; echo "Signed $i"; done

TARNAME=libqt5pas_"$MAJORVER"_"$MINORVER"_"$EXTRAVER"-"$PACKVER"_"$ARCH"
rm -Rf "$TARNAME"
mkdir "$TARNAME"
cp targz.readme "$TARNAME"/.
cp ../"$FULLLIBNAME" "$TARNAME"/.
tar czf "$TARNAME".tar.gz "$TARNAME"
rm -Rf "$TARNAME"
rm -Rf BUILD
ls -ltr

echo "---------------- DEB Lintian Results ----------------------------"

lintian -IiE *.deb

echo "---------------- RPM Lint Results --------------------------------"
rpmlint -i *.rpm

# --------------- RPM LINT Issues ------------------------------

# This relates to the Obsolete: directives necessary to get it to overwrite
# the range of libqt5pas packages in the RPM world. If I do as it demands,
# add in anoth Provides: xxx it just generates more, scary messages.

# libqt5pas.armv7hl: W: obsolete-not-provided lib64qt5pas1
# If a package is obsoleted by a compatible replacement, the obsoleted package
# should also be provided in order to not cause unnecessary dependency breakage.
# If the obsoleting package is not a compatible replacement for the old one,
# leave out the Provides.


# libqt6pas6.x86_64: E: library-without-ldconfig-postin
# libqt6pas6.x86_64: E: library-without-ldconfig-postun
#    Not required anymore -
#    https://fedoraproject.org/wiki/Changes/Removing_ldconfig_scriptlets

# libqt6pas6.x86_64: W: invalid-license see /usr/share/doc/libqt6pas6/copyright
#    The license is fine, its just that rpmlint cannot parse it.

# libqt6pas6.x86_64: E: no-signature
#    As near as I can tell, only OpenSUSE seems to care about signitures.

# no-binary
#    Rpmlint thinks it should be "noarch" because there is no binary but 
#    it provides a symling, in an appropriate binary dir, to a binary !

# --------------- Lintian Issues ---------------------------------

# No-Symbol-control-file
#    Yeah, no symbol control file.

# No-hardening
#    Personally, I don't thing hardening is needed in the sort of apps
#    likely to be working with this library but I am happy to hear any
#    other opinions on this matter. Its easy to do but a bit slower.
#    And its really a decision for the Lazarus Qt6 developer.


