#!/bin/bash
set -e

#  Copyright (C) 2022 David Bannon
#
#    License:
#    This code is licensed under BSD 3-Clause Clear License, see 
#    https://spdx.org/licenses/BSD-3-Clause-Clear.html

# A short script to build RPM Packages for the LibQt5Pas Library for Lazarus.
# Requires the prebuilt library (one directory up) and the commands rpm and rmplint
# Should work on x86_64, armhf, aarch64

PRODUCT="libqt5pas"			# used in package name
LIBNAME=libQt5Pas			# used in actual binary file

M_ARCH=`uname -m`	# Might return, eg aarch64, x86_64. Raspi running 32bit returns armv7l - possibly RasPi version specific ?
CURRENT=`pwd`
PACKVER='1'		# should start at '1', rev if you re-package same binary after release


cd ..			# we expect to find binary one dir above
LIBFILE=$(find . -maxdepth 1 ! -type l  -name "$LIBNAME""*")
cd $CURRENT
MAJORVER=`echo $LIBFILE | awk -F"." '{ printf $4 }'`	# for 6.2.0, = 7
MINORVER=`echo $LIBFILE | awk -F"." '{ printf $5 }'`	#	     = 2
EXTRAVER=`echo $LIBFILE | awk -F"." '{ printf $6 }'`	#	     = 0
VERSION="$MAJORVER"."$MINORVER"."$EXTRAVER"

FULLLIBNAME="$LIBNAME".so."$VERSION"

# Depends on -
# $VERSION  set above
# $PACKVER  manually set above
# $PRODUCT  manually set above, eg libqt6pas6 or libqt5pas (lowercase, used in package name)
# $ARCH     done in SetUpArch
# $M_ARCH   set above.
# $RDIR_ARCH done in SetUpArch
# $CURRENT  done above
# $FULLLIBNAME done above
# Assumes changelog is up to date
# Both Specfiles are available

# following is unchanged copy from libqt6 version, except for pas and spec file names

function MakeRPM () {
	# PARTVER="$MAJORVER"."$MINORVER"."$EXTRAVER"
	FULLVER="$VERSION"-"$PACKVER"
    RDIR="$PRODUCT"-"$VERSION"
    echo "=== Making RPM from $PRODUCT"."$FULLVER"_"$ARCH.deb in "["$RDIR"]" ==="
    rm -Rf "$RDIR"
	mkdir -p "$RDIR"/usr/"$RDIR_ARCH"
	chmod 744 "$RDIR"/usr/"$RDIR_ARCH"
	# mkdir -p "$RDIR"/usr/lib
	if [ "$1" = "devel" ]; then		# DEV Package
		echo "========= RPM Devel Package ========"
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"-devel
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"-devel
    	cp copyright "$RDIR"/usr/share/doc/"$PRODUCT"-devel/copyright
		gzip -knc --best changelog.libqt5pas >> "$RDIR"/usr/share/doc/"$PRODUCT"-devel/changelog.gz
		# ln -s "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so

		cd "$RDIR"/usr/"$RDIR_ARCH"
		ln -s "$FULLLIBNAME" "$LIBNAME".so
		cd "$CURRENT"		
		
    	cp ../qt5.pas "$RDIR/usr/share/doc/"$PRODUCT"-devel/."
		cp libqt5pas-devel.spec "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_DEPEND/${PRODUCT} = ${VERSION}, qt5-qtbase-devel/" "$RDIR"/"$PRODUCT".spec
		# sed -i "s/INSERT_DEPEND/${PRODUCT} = ${MAJORVER}.${VERSION}/" "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_RDIR/${RDIR}/" "$RDIR"/"$PRODUCT".spec
	else	
		echo "==== RPM Lib Package FULLLIBNAME $FULLLIBNAME ==="
		mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT"
		chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT"
    	cp copyright "$RDIR/usr/share/doc/"$PRODUCT"/copyright"
		gzip -knc --best changelog.libqt5pas >> "$RDIR"/usr/share/doc/"$PRODUCT"/changelog.gz
		cp ../"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/.
		chmod 755 "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
		ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"
		cp libqt5pas.spec "$RDIR"/"$PRODUCT".spec
		sed -i "s/INSERT_RDIR/${RDIR}/" "$RDIR"/"$PRODUCT".spec
		# rpmbuild seems to workout dependencies fine but does not specify a needed version
	fi
	sed -i "s/^Version:*./Version: ${VERSION}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/^Release:*./Release: ${PACKVER}/" "$RDIR"/"$PRODUCT".spec
	sed -i "s/INSERT_FULL_VER/Version: ${FULLVER}/" "$RDIR"/"$PRODUCT".spec
    sed -i "s/INSERT_EXTRAVER/${EXTRAVER}/" "$RDIR"/"$PRODUCT".spec
	cp "$RDIR"/"$PRODUCT".spec "$PRODUCT""$1".spec-just-used
	cd "$RDIR"

echo "------ In Make RPM, done stuff, arch=$M_ARCH, current=$CURRENT, rdir=$RDIR, product=$PRODUCT"


	fakeroot rpmbuild --target "$M_ARCH" --buildroot "$CURRENT"/"$RDIR" -bb "$PRODUCT".spec
	cd .. 
}

# following code (but not function) is unchanged copy from libqt6 version

function SetUpArch () {
	if [ "$M_ARCH" == "aarch64" ]; then
		ARCH="arm64"			# Name used in deb file name
		DIR_ARCH="aarch64-linux-gnu"	# Dir where the libraries end up
		RDIR_ARCH="lib64"		# Where RPMs put the library         TODO !!!
	fi
	if [ "$M_ARCH" == "armv7l" ]; then
		ARCH="armhf"
		DIR_ARCH="arm-linux-gnueabihf"
		RDIR_ARCH="lib"		# Where RPMs put the library         TODO !!!
	fi
	if [ "$M_ARCH" == "x86_64" ]; then
		ARCH="amd64"
		DIR_ARCH="x86_64-linux-gnu"
		RDIR_ARCH="lib64"		# Where RPMs put the library 
	fi
	if [ "$ARCH" == "unknown" ]; then
		echo "ERROR cannot id your arch $DIR_ARCH, exiting..."
		exit
	fi
}


strip --remove-section=.comment ../"$FULLLIBNAME"
SetUpArch
echo "Arch setup version=$VERSION"
MakeRPM   
echo "MakeRPM version=$VERSION"
MakeRPM "devel" 
echo "MakeDev version=$VERSION"

rpmlint -i *.rpm

